from .constants import (
    APP_NAME,
    APP_SUBTITLE,
    APP_VERSION,

    # Cores gerais.
    COR_ALERTA,
    COR_ERRO,
    COR_FUNDO,
    COR_SUCESSO,

    # Identidade visual — ZELURBIS.
    VERDE_SIDEBAR,
    VERDE_SIDEBAR_ATIVO,
    VERDE_DESTAQUE,

    # Identidade visual — módulos.
    COR_ECOACAI,
    COR_ECOOLEO,
    COR_ECOGARRAFAS,

    # Domínio.
    SETORES,
    MARCAS_VEICULOS,
    TIPOS_VEICULOS,
    CAPACIDADES_VEICULOS,
    ANOS_VEICULOS,

    # Status.
    StatusSolicitacao,
    StatusColeta,
    StatusVeiculo,
    STATUS_SOLICITACOES,
    STATUS_SOLICITACAO_PENDENTE,
    STATUS_SOLICITACAO_AGENDADA,
    STATUS_SOLICITACAO_EM_DESLOCAMENTO,
    STATUS_SOLICITACAO_EM_COLETA,
    STATUS_SOLICITACAO_CONCLUIDA,
    STATUS_SOLICITACAO_CANCELADA,
    STATUS_VEICULOS,
    STATUS_VEICULO_DISPONIVEL,
    STATUS_VEICULO_EM_COLETA,
    STATUS_VEICULO_MANUTENCAO,
    STATUS_VEICULO_INATIVO,
)