from .constants import (
    APP_NAME,
    APP_SUBTITLE,
    APP_VERSION,
    COR_ALERTA,
    COR_CARD,
    COR_ERRO,
    COR_FUNDO,
    COR_PRIMARIA,
    COR_SECUNDARIA,
    COR_SUCESSO,
    COR_TEXTO,
    SETORES,

    STATUS_SOLICITACOES,

    STATUS_SOLICITACAO_PENDENTE,
    STATUS_SOLICITACAO_AGENDADA,
    STATUS_SOLICITACAO_EM_DESLOCAMENTO,
    STATUS_SOLICITACAO_EM_COLETA,
    STATUS_SOLICITACAO_CONCLUIDA,
    STATUS_SOLICITACAO_CANCELADA,
)